[package]
name = "mp4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.59"
mp4-box = { path = "../mp4-box" }
mp4-derive = { path = "../mp4-derive" }
tokio = { version = "1.23.0", features = ["io-util"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
