on: push

jobs:
  build_cache:
    runs-on: ubuntu-latest

    env:
      RUSTC_FORCE_INCREMENTAL: 1

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/cache_cargo
      - name: build
        run: cargo build
      - name: clippy
        run: cargo clippy
      - name: Download sample file
        run: wget https://download.samplelib.com/mp4/sample-5s.mp4

  fmt:
    runs-on: ubuntu-latest

    needs: build_cache

    steps:
      - uses: actions/checkout@v2

      - run: rustup component add rustfmt
      - uses: ./.github/actions/cache_cargo
      - name: fmt
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest

    env:
      RUSTC_FORCE_INCREMENTAL: 1

    needs: build_cache

    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - uses: ./.github/actions/cache_cargo
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    runs-on: ubuntu-latest
    env:
      RUSTC_FORCE_INCREMENTAL: 1

    needs: build_cache

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/cache_cargo
      - name: test
        run: cargo test --all -- --nocapture